// <auto-generated />
namespace ChefsWonders.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Modelchange250919 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modelchange250919));
        
        string IMigrationMetadata.Id
        {
            get { return "201909250839218_Modelchange250919"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
