// <auto-generated />
namespace ChefsWonders.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ordermodelchange2709201901 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ordermodelchange2709201901));
        
        string IMigrationMetadata.Id
        {
            get { return "201909270500081_ordermodelchange2709201901"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
